version: '3.8'

services:
  app:
    build: .
    command: bash -c 'uvicorn api:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_USERNAME=${EDU_DATABASE_USERNAME:-mongoadmin}
      - DATABASE_PASSWORD=${EDU_DATABASE_PASSWORD:-P@SSWD22}
      - DATABASE_HOST=${EDU_DATABASE_HOST:-mongo}
      - DATABASE_PORT=${EDU_DATABASE_PORT:-27017}
      - DATABASE_NAME=${EDU_DATABASE_NAME:-edu_db}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${EDU_DATABASE_USERNAME:-mongoadmin}
      - MONGO_INITDB_ROOT_PASSWORD=${EDU_DATABASE_PASSWORD:-P@SSWD22}

volumes:
  edu_app_volumes:
